apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://paul:paulpass@postgres-service:5432/itemsdb
  SECRET_KEY: change_this_to_a_long_random_secret
